# Generated by Django 5.0.4 on 2024-05-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_favoriteproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='icon',
        ),
    ]
