# Generated by Django 5.0.4 on 2024-06-18 13:57

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(max_length=200, upload_to=product.models.upload_to, verbose_name='image'),
        ),
    ]
