# Generated by Django 5.0.4 on 2024-06-18 13:57

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_pic_to, verbose_name='Photo'),
        ),
    ]
