# Generated by Django 5.0.4 on 2024-05-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default=1, max_length=50, verbose_name='currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default=1, max_length=50, verbose_name='language'),
            preserve_default=False,
        ),
    ]
