# Generated by Django 5.0.4 on 2024-08-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Code"
            ),
        ),
    ]
