# Generated by Django 5.0.4 on 2024-05-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_currency_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(max_length=10, verbose_name='currency'),
        ),
    ]
