# Generated by Django 5.0.4 on 2024-05-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='notify_followers',
            field=models.BooleanField(default=False, verbose_name='notify followers'),
        ),
    ]
