# Generated by Django 5.0.4 on 2024-05-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='news',
        ),
    ]
