# Generated by Django 5.0.4 on 2024-05-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
