# Generated by Django 5.0.4 on 2024-06-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_order_tip'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('paypal', 'paypal'), ('bank_transfer', 'bank transfer')], default='cash', max_length=50, verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('on_the_way', 'on the way'), ('ready', 'ready'), ('canceled', 'canceled'), ('delivered', 'delivered')], default='processing', max_length=50, verbose_name='order status'),
        ),
    ]
