# Generated by Django 5.0.4 on 2024-05-04 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'seller',
                'verbose_name_plural': 'sellers',
                'db_table': 'seller',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('icon', models.FileField(max_length=200, upload_to='seller/category', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'seller category',
                'verbose_name_plural': 'seller categories',
                'db_table': 'seller_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('company_ceo', models.CharField(max_length=225, verbose_name='company ceo')),
                ('company_vat_id', models.CharField(max_length=225, verbose_name='company vat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'seller profile',
                'verbose_name_plural': 'seller profiles',
                'db_table': 'seller_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
