# Generated by Django 5.0.4 on 2024-05-06 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='seller/', verbose_name='cover photo'),
        ),
        migrations.AddField(
            model_name='seller',
            name='product_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='discount all product'),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='seller/', verbose_name='profile photo'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='seller.sellercategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='delivery_terms_distance',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='delivery distance'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='delivery_terms_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='delivery price'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
    ]
