# Generated by Django 5.0.4 on 2024-05-05 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='ceo',
            field=models.CharField(default=1, max_length=225, verbose_name='company ceo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='closing_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='closing hour'),
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='seller',
            name='opening_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='opening hour'),
        ),
        migrations.AddField(
            model_name='seller',
            name='vat',
            field=models.CharField(default=1, max_length=225, verbose_name='company vat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='seller.sellercategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=255, verbose_name='company name'),
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
