# Generated by Django 5.0.4 on 2024-05-07 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='product_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='discount all product'),
        ),
    ]
