# Generated by Django 5.0.4 on 2024-05-12 13:37

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_seller_product_discount'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seller',
            managers=[
                ('is_verified', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='is subscribed'),
        ),
    ]
